--Steven Rollo; CS299-03; Spring 2017
--
--2_dropAdvertTSQL.sql
--
--Final Paper Advert Schema - 5/12/2017

SELECT 'Steven Rollo - CS299 Final Papaer 2_dropAdvertTSQL.sql' ASSIGNMENT;
SELECT 'Dropping Views and Tables' SECTION_01;
--Added conitional drop statements
DROP VIEW IF EXISTS INVOICE;
DROP VIEW IF EXISTS ADVERTISER;
DROP VIEW IF EXISTS AD_PRICE;
DROP TABLE IF EXISTS AD_RUN;
DROP TABLE IF EXISTS PAYMENT;
DROP TABLE IF EXISTS INVOICE_T;
DROP TABLE IF EXISTS PRICE_REQUEST;
DROP TABLE IF EXISTS AD;
DROP TABLE IF EXISTS RATE_CARD;
DROP TABLE IF EXISTS CONTACT_INFO;
DROP TABLE IF EXISTS ADVERTISER_T;

SELECT 'Dropping Triggers' SECTION_02;
DROP TRIGGER update_ad_runs;
DROP TRIGGER delete_ad_runs;


